<?php

declare(strict_types=1);

namespace App\Contracts;

interface EmbeddingDriverInterface
{
    /**
     * Generate an embedding for the given text.
     *
     * @param  string  $text
     * @return array<float>
     */
    public function embed(string $text): array;

    /**
     * Get the name of the driver.
     *
     * @return string
     */
    public function getName(): string;

    /**
     * Check if the driver is healthy and available.
     *
     * @return bool
     */
    public function isHealthy(): bool;

    /**
     * Get the dimensions of the embeddings generated by this driver.
     *
     * @return int
     */
    public function getDimensions(): int;
}